# This is a basic workflow to help you get started with Actions

name: ServicesWorkflow

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./Services

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: execute py script # run sj-gobierno.py to get the latest data
        working-directory: ${{env.working-directory}}
        run: python helloWorld.py
