# This is a basic workflow to help you get started with Actions

name: ServicesWorkflow

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Services

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: execute py script # run sj-gobierno.py to get the latest data
        run: python helloWorld.py
